import mongoose from "mongoose";

const timetableSchema = new mongoose.Schema(
  {
    // Basic identification
    name: {
      type: String,
      required: [true, "Timetable name is required"],
      trim: true,
    },
    description: {
      type: String,
      trim: true,
    },

    // Academic context
    academicSession: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "AcademicSession",
      required: [true, "Academic session is required"],
      index: true,
    },
    semester: {
      type: Number,
      required: [true, "Semester is required"],
      min: [1, "Semester must be at least 1"],
      max: [8, "Semester cannot exceed 8"],
    },
    program: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Program",
      required: [true, "Program is required"],
    },
    section: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Section",
      required: [true, "Section is required"],
    },

    // Schedule entries
    schedule: [
      {
        day: {
          type: String,
          enum: [
            "Monday",
            "Tuesday",
            "Wednesday",
            "Thursday",
            "Friday",
            "Saturday",
            "Sunday",
          ],
          required: true,
        },
        timeSlot: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "TimeSlot",
          required: true,
        },
        courseAllocation: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "CourseAllocation",
          required: true,
        },
        room: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Room",
        },
        // For tracking changes
        isModified: {
          type: Boolean,
          default: false,
        },
        notes: {
          type: String,
          trim: true,
        },
      },
    ],

    // Schedule metadata
    totalHoursPerWeek: {
      type: Number,
      default: 0,
      min: [0, "Total hours cannot be negative"],
    },
    totalCourses: {
      type: Number,
      default: 0,
      min: [0, "Total courses cannot be negative"],
    },

    // Status
    status: {
      type: String,
      enum: ["draft", "published", "archived", "rejected"],
      default: "draft",
    },
    version: {
      type: Number,
      default: 1,
      min: [1, "Version must be at least 1"],
    },

    // Approval workflow
    isApproved: {
      type: Boolean,
      default: false,
    },
    approvedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    approvedAt: {
      type: Date,
    },
    rejectionReason: {
      type: String,
      trim: true,
    },

    // Generation info
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
    generationMethod: {
      type: String,
      enum: ["manual", "auto", "hybrid"],
      default: "manual",
    },

    // Constraints and preferences
    constraints: {
      noBackToBackClasses: {
        type: Boolean,
        default: false,
      },
      maxDailyHours: {
        type: Number,
        default: 8,
      },
      preferMorningSlots: {
        type: Boolean,
        default: true,
      },
      preferLabAfternoons: {
        type: Boolean,
        default: true,
      },
    },

    // Performance metrics
    teacherSatisfaction: {
      type: Number,
      min: [0, "Satisfaction must be between 0-100"],
      max: [100, "Satisfaction must be between 0-100"],
    },
    roomUtilization: {
      type: Number,
      min: [0, "Utilization must be between 0-100"],
      max: [100, "Utilization must be between 0-100"],
    },

    // Audit trail
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    lastModifiedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    publishedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    publishedAt: {
      type: Date,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  },
);

// Compound indexes
timetableSchema.index(
  { academicSession: 1, semester: 1, program: 1, section: 1 },
  { unique: true, partialFilterExpression: { status: { $ne: "archived" } } },
);
timetableSchema.index({ program: 1, semester: 1 });
timetableSchema.index({ status: 1, academicSession: 1 });

// Virtual for days count
timetableSchema.virtual("daysCount").get(function () {
  if (!Array.isArray(this.schedule)) return 0;

  const uniqueDays = [...new Set(this.schedule.map((entry) => entry.day))];
  return uniqueDays.length;
});

// Virtual for conflict status
timetableSchema.virtual("hasConflicts").get(function () {
  if (!Array.isArray(this.schedule)) return false;

  const teacherConflicts = {};
  const roomConflicts = {};

  for (const entry of this.schedule) {
    const key = `${entry.day}-${entry.timeSlot}`;

    if (entry.courseAllocation?.teacher) {
      const teacherKey = `${key}-${entry.courseAllocation.teacher}`;
      if (teacherConflicts[teacherKey]) return true;
      teacherConflicts[teacherKey] = true;
    }

    if (entry.room) {
      const roomKey = `${key}-${entry.room}`;
      if (roomConflicts[roomKey]) return true;
      roomConflicts[roomKey] = true;
    }
  }
  return false;
});

// Pre-save middleware to calculate totals
timetableSchema.pre("save", async function () {
  if (this.schedule && this.schedule.length > 0) {
    // Calculate total courses
    const uniqueCourses = [
      ...new Set(
        this.schedule.map((entry) =>
          entry.courseAllocation?.course?.toString(),
        ),
      ),
    ].filter(Boolean);
    this.totalCourses = uniqueCourses.length;

    // Calculate total hours
    let totalHours = 0;
    for (const entry of this.schedule) {
      const timeSlot = await mongoose
        .model("TimeSlot")
        .findById(entry.timeSlot);
      if (timeSlot) {
        totalHours += timeSlot.durationMinutes / 60;
      }
    }
    this.totalHoursPerWeek = parseFloat(totalHours.toFixed(2));
  }

  // Increment version if schedule changed
  if (this.isModified("schedule") && !this.isNew) {
    this.version += 1;
  }
});

// Method to check for conflicts
timetableSchema.methods.checkConflicts = async function () {
  const conflicts = {
    teacherConflicts: [],
    roomConflicts: [],
    timeConflicts: [],
  };

  const teacherSchedule = {};
  const roomSchedule = {};
  const courseSchedule = {};

  for (const entry of this.schedule) {
    const timeSlot = await mongoose.model("TimeSlot").findById(entry.timeSlot);
    if (!timeSlot) continue;

    const key = `${entry.day}-${entry.timeSlot}`;

    // Check teacher conflicts
    if (entry.courseAllocation?.teacher) {
      const teacherKey = `${key}-${entry.courseAllocation.teacher}`;
      if (teacherSchedule[teacherKey]) {
        conflicts.teacherConflicts.push({
          day: entry.day,
          timeSlot: timeSlot.timeRange,
          teacher: entry.courseAllocation.teacher,
          conflictingEntry: teacherSchedule[teacherKey],
        });
      } else {
        teacherSchedule[teacherKey] = {
          course: entry.courseAllocation?.course,
          section: this.section,
        };
      }
    }

    // Check room conflicts
    if (entry.room) {
      const roomKey = `${key}-${entry.room}`;
      if (roomSchedule[roomKey]) {
        conflicts.roomConflicts.push({
          day: entry.day,
          timeSlot: timeSlot.timeRange,
          room: entry.room,
          conflictingEntry: roomSchedule[roomKey],
        });
      } else {
        roomSchedule[roomKey] = {
          course: entry.courseAllocation?.course,
          teacher: entry.courseAllocation?.teacher,
        };
      }
    }

    // Check same course at same time in different sections (if applicable)
    if (entry.courseAllocation?.course) {
      const courseKey = `${key}-${entry.courseAllocation.course}`;
      if (courseSchedule[courseKey]) {
        conflicts.timeConflicts.push({
          day: entry.day,
          timeSlot: timeSlot.timeRange,
          course: entry.courseAllocation.course,
          conflictingEntry: courseSchedule[courseKey],
        });
      } else {
        courseSchedule[courseKey] = {
          teacher: entry.courseAllocation?.teacher,
          section: this.section,
        };
      }
    }
  }

  return conflicts;
};

// Method to generate timetable matrix
timetableSchema.methods.getTimetableMatrix = async function () {
  const days = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"];
  const timeSlots = await mongoose
    .model("TimeSlot")
    .find({ isActive: true })
    .sort("slotNumber");

  const matrix = {};

  for (const day of days) {
    matrix[day] = {};
    for (const timeSlot of timeSlots) {
      matrix[day][timeSlot._id] = null;
    }
  }

  for (const entry of this.schedule) {
    if (matrix[entry.day] && matrix[entry.day][entry.timeSlot] === null) {
      matrix[entry.day][entry.timeSlot] = entry;
    }
  }

  return {
    days,
    timeSlots,
    matrix,
  };
};

const Timetable = mongoose.model("Timetable", timetableSchema);

export default Timetable;
